mysql:
  host: 49.235.71.44
  port: 3306
  username: root
  password: hsje$@hwqw$#
  database: KoKoChatting

jwt:
  secret:  NtKBdzmI06iRf6u6

logger:
  level: debug
  ginlog: ./logs/gin.log
  serverlog: ./logs/server.log


server:
  port: 8080
  max-wsconn-num: 200
  websocket:
    health-check-duration: 600      # 单位为s
    filter-offline-conn-duration: 600
    enable-compression: false