mysql:
  host: 47.96.71.248
  port: 3306
  username: root
  password: hsje$@hwqw$#
  database: KoKoChatting

jwt:
  secret: sadadfgs&*^dfkasI*&(*  # 密钥需要修改

logger:
  level: debug
  ginlog: ./logs/gin.log
  serverlog: ./logs/server.log


server:
  port: 8080
  max-wsconn-num: 200
  websocket:
    health-check-duration: 30      # 单位为s
    filter-offline-conn-duration: 60
    enable-compression: false